name: Sync to Gitee
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:baijingfeng/bookmarks.git'
          destination-repo: 'git@gitee.com:baijingfeng/bookmarks.git'

      - name: Auto Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with: 
          gitee-username: baijingfeng
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: baijingfeng/bookmarks.git